

socket-server:
  port: 8085
    #write your ip address not localhost if you want to try with other devices on lan
  host: 192.168.0.10


server:
  port: 8500
  servlet:
    contextPath: /api

# local
spring:
  main:
    allow-circular-references: true
  datasource:
    initialization-mode: never
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chat
    password: celal371
    username: postgres
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql:false: